console.log("(10 > 5)");
console.log(10 > 5);
console.log('("10" > 5)');
console.log("10" > 5);
console.log("(true > 5)");
console.log(true > 5);
console.log("Number(true)");
console.log(Number(true));
console.log("true == 1");
console.log(true == 1);
console.log("true === 1");
console.log(true === 1);
console.log("true !== 1");
console.log(true !== 1);
